import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { FlowerBG } from "./_components/FlowerBG";
import { UserButton } from "./_components/UserButton";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.variable}`}>
        <body className="relative">
          <FlowerBG />
          <audio
            src="https://x8cti9ppp0.ufs.sh/f/fR4eWtZ8tDgy6zkQQUqftzpgsLlmKwU2SridI5YX3u0aCJPR"
            autoPlay
            loop
            muted
            className="hidden"
          />
          <div className="relative z-10">
            <header className="absolute top-4 right-4">
              <UserButton />
            </header>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
